[DisplaySettings]
width=800
height=600
fps=60

[GameMode]
; debug, normal
mode=debug

[Flags]
;set these to True or False to change certain behaviours in the game
;verbosecombat = will print strings describing in detail why the AI makes its decisions
verbosecombat=True